### ISSUE TITLE
Data not found

### ISSUE THREAD

**Issue by Muhammad-Mubeen** [mhas97/SwingMetrics#1]
Hie, thank you for uploading this, my query is, where are you saving the data? I didn't find any local file or reference to any server to save the generated data. It just shows start and stop button nothing else, Where data is going?

**Comment by mhas97** [comment]
The data is saved to the local storage for the Samsung Gear watch when the stop button is pressed. This is done in the save_data function.

**Comment by Muhammad-Mubeen** [comment]
@mhas97 thank you for the reply. Issue was with the given path. Application wasn't allowed to read or write data on the given path so I gave the path where Tizen saves the TPK of the application and it worked.

Another question, how I can give access to my application to read and write data on the path which you mentioned in your code?

Note: I have given the privileges of read, write and data storage to my application.
